.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vexta_qt test_vexta_qt
clean: FORCE
	$(MAKE) -C .. vexta_qt_clean test_vexta_qt_clean
check: FORCE
	$(MAKE) -C .. test_vexta_qt_check
vexta-qt vexta-qt.exe: FORCE
	 $(MAKE) -C .. vexta_qt
apk: FORCE
	$(MAKE) -C .. vexta_qt_apk
