server=1
listen=1

# Uncomment after the first public Vexta bootstrap node is deployed.
# addnode=BOOTSTRAP_NODE_IP
txindex=1

rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=vextarpc
rpcpassword=CHANGE_THIS_PASSWORD

fallbackfee=0.001
dandelion=0

logtimestamps=1
debug=0
